config/routes.rb
Rails.application.routes.draw do
  resources :foods
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
    validates :name, :description, presence:true
    validates :price, numericality: { greater_than_or_equal_to:0.01 }
    validates :name, uniqueness:true
    validates :image_url, allow_blank:true, format: {
        with: %r{\.(gif|jpg|png)\Z}i,
        message:'must be a URL for GIF, JPG or PNG image.'
    }

    def self.by_letter(letter)
        where("name LIKE ?", "#{letter}%").order(:name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]

  # GET /foods
  # GET /foods.json
  def index
    @foods = params[:letter].nil? ? Food.all : Food.by_letter(params[:letter])
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_params
      params.require(:food).permit(:name, :description, :image_url, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_form.html.erb
<%= form_for(food) do |f| %>
  <% if food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
      <% food.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, rows: 10, cols: 60 %>
  </div>

  <div class="field">
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing Food</h1>

<%= render 'form', food: @food %>

<%= link_to 'Show', @food %> |
<%= link_to 'Back', foods_path %>

app/views/foods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Foods</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Image url</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @foods.each do |food| %>
      <tr>
        <td><%= food.name %></td>
        <td><%= food.description %></td>
        <td><%= food.image_url %></td>
        <td><%= food.price %></td>
        <td><%= link_to 'Show', food %></td>
        <td><%= link_to 'Edit', edit_food_path(food) %></td>
        <td><%= link_to 'Destroy', food, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food', new_food_path %>

app/views/foods/new.html.erb
<h1>New Food</h1>

<%= render 'form', food: @food %>

<%= link_to 'Back', foods_path %>

app/views/foods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @food.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @food.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @food.image_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @food.price %>
</p>

<%= link_to 'Edit', edit_food_path(@food) %> |
<%= link_to 'Back', foods_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bncc</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= controller.controller_name %>">
    <%= yield %>
  </body>
</html>